import './globals.css'

export const metadata = {
  title: 'Hipnode',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-source-sans-pro'>
      <body>{children}</body>
    </html>
  )
}
