import './globals.css'
import Providers from '../components/Providers'
import Provider from '@components/Provider'

export const metadata = {
  title: 'Hipnode',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-source-sans-pro' suppressHydrationWarning>
      <body>
        <Provider>
          <Providers>
            {children}
          </Providers>
        </Provider>
      </body>
    </html>
  )
}
